spring.application.name=backend

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/intranet
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: MinhaChaveSuperSecretaJWT2026IntranetSistema123456789
  expiration: 28800000
